### PR TITLE
Makefile change to locate SPARK_HOME

### PR DESCRIPTION
**Pull request by arundasan91**
awk does not seem to work. Please confirm. 
We missed to include this in the previous pull request.
Thanks.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by arundasan91** [comment]
Hello @anfeng ,

I came across an error while installing CoS on a fresh ubuntu instance installed with Hadoop 2.7.1 and Spark 2.0.0. Spark version is still not being fetched since SPARK_HOME is not set properly. Please see this:

```
ifeq ($(shell which spark-submit), "")
     SPARK_HOME ?=/home/y/share/spark
     $(info $$SPARK_HOME_DEFAULT is [${SPARK_HOME}])
else
     SPARK_HOME ?=$(shell which spark-submit 2>&1 | sed 's/\/bin\/spark-submit//g')
     $(info $$SPARK_HOME_LOCAL is [${SPARK_HOME}])
endif
$(info $$HOME is [${HOME}])
```

Log:
```
cc@arun-master:~/CaffeOnSpark$ sudo make clean
$SPARK_HOME_LOCAL is []
$HOME is [/home/cc]
cd caffe-public; make clean; cd ..
make[1]: Entering directory `/home/cc/CaffeOnSpark/caffe-public'
make[1]: Leaving directory `/home/cc/CaffeOnSpark/caffe-public'
cd caffe-distri; make clean; cd ..
make[1]: Entering directory `/home/cc/CaffeOnSpark/caffe-distri'
mvn clean
```

**Comment by anfeng** [comment]
You need to either set spark_home or have its bin included in path.

Andy Feng

**Comment by arundasan91** [comment]
I have both set-up.
Please see my `.bashrc`

```
export SPARK_HOME=/usr/local/spark
export PATH=$PATH:$SPARK_HOME/bin
```

I can do `which spark-submit` in my logged in session.
```
cc@arun-master:~$ which spark-submit
/usr/local/spark/bin/spark-submit
```

**Comment by anfeng** [comment]
Maybe you don't have sed available?

Andy Feng

**Comment by arundasan91** [comment]
Checked that. I will try again in another system.
```
cc@arun-master:~$ sed
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
  -e script, --expression=script
                 add the script to the commands to be executed
..........
..........
```

**Comment by anfeng** [comment]
Will it make a difference if you replace '?=' by '='?

**Comment by arundasan91** [comment]
I tried it with `=`, `:=`. Both did not work.

**Comment by anfeng** [comment]
You may want to check your make manual. Your new system may use a different Make tool. Try "make --version"

**Comment by arundasan91** [comment]
Make version is the same as my old machine.

```
cc@arun-master:~$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
```

**Comment by anfeng** [comment]
Maybe you should echo the ${SPARK_HOME} and $(shell which spark-submit) before the conditional assignment? On your shell, you could try 
> which spark-submit 2>&1 | sed 's/\/bin\/spark-submit//g'

**Comment by arundasan91** [comment]
Yes. I tried each commands in shell separately and all of them (except awk) did work.

```
cc@arun-master:~$ which spark-submit 2>&1 | sed 's/\/bin\/spark-submit//g'
/usr/local/spark
cc@arun-master:~$ ${SPARK_HOME}/bin/spark-submit --version 2>&1 | grep version | cut -d' ' -f10 | cut -d'.' -f1
2
cc@arun-master:~$ ${SPARK_HOME}/bin/spark-submit --version 2>&1 | grep version | awk '{print $$5}' | cut -d'.' -f1

cc@arun-master:~$

```

**Comment by arundasan91** [comment]
I just confirmed this with another Ubuntu 14.04 instance. Spark version variable is not set in Makefile, awk does not work in line 13.

I will try an Ubuntu 16 instance later today.

**Comment by arundasan91** [comment]
Update:

In a fresh Ubuntu 16 instance with `sed`, `awk`, without setting `SPARK_HOME` or its bin as environment variables or in `.bashrc`, I tried `sudo make clean` after adding these lines:
```
ifeq ($(shell which spark-submit), "")
     SPARK_HOME ?=/home/y/share/spark
     $(info $$SPARK_HOME_DEFAULT is [${SPARK_HOME}])
else
     SPARK_HOME ?=$(shell which spark-submit 2>&1 | sed 's/\/bin\/spark-submit//g')
     $(info $$SPARK_HOME_LOCAL is [${SPARK_HOME}])
endif
```
According to your logic, if spark-submit does not work, then SPARK_HOME must be set as `SPARK_HOME =/home/y/share/spark`.    
However, the logic `ifeq ($(shell which spark-submit), "")` fails and I get this as the output when I do `make clean`:
```
$SPARK_HOME_LOCAL is []
```
I looked into this issue and found that changing the condition to the below mentioned logic does work:
```
ifeq ($(shell which spark-submit),)
```
I think the `if` condition did not take `""` as NULL character. I added a test flag in Makefile (which did nothing) for simplicity. With this change, I get:
```
cc@arun-master:~/CaffeOnSpark$ make test
$SPARK_HOME_DEFAULT is [/home/y/share/spark]
make: 'test' is up to date.
```

**Comment by anfeng** [comment]
Please change: 
`ifeq ($(shell which spark-submit),"")
`
to
`ifeq ($(shell which spark-submit),)
`

**Comment by arundasan91** [comment]
changes in if condition corrects awk part in line 13.
Successfully used `mvn -Dspark2 clean` 

Shall I take my changes to line 13 off ?

**Comment by anfeng** [comment]
Yeah, let's minimize our changes.

**Comment by arundasan91** [comment]
Reverted back to awk. This was a bit tricky to debug :)
Thanks for the help and directions. I'm learning a lot these days.

**Comment by anfeng** [comment]
+1

**Pull request merged**
