### PR TITLE
SPARK_VERSION in Makefile

### PR DESCRIPTION
**Pull request by arundasan91**
Makefile was not fetching SPARK_VERSION properly because `awk` wasn't working with the rest. Changed `awk` with `cut` to do the same thing.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by anfeng** [comment]
SPARK_VERSION should only be visible to Makefile. Please try the following:
   * Have SPARK_HOME point to your Spark 2 installation
   * Run "make clean" You should see the following entry in the log: `mvn -Dspark2 clean`

**Comment by arundasan91** [comment]
I wanted to raise that point as well. Does this mean that users will have to update SPARK_HOME variable in Makefile the first time they set up CaffeOnSpark ?

Can we use already existing ENV variables like $SPARK_HOME inside Makefile ? I searched for this but found very little info on this.

**Comment by arundasan91** [comment]
I suppose Makefile should be able to see the env variables ?

**Comment by arundasan91** [comment]
Shall I add this:
```
sed -i 's|SPARK_HOME ?=/home/y/share/spark|SPARK_HOME ?=$SPARK_HOME|g' Makefile
```
just before we run `make build` so that the SPARK_HOME will be updated automatically and we'll get the rest of the portion requiring SPARK_HOME including the SPARK_VERSION running correctly.

Please take a look.

**Comment by anfeng** [comment]
Makefile has access to SPARK_HOME defined in your shell. Do you have SPARK_HOME defined there?

Alternatively, we could enhance Makefile as below. 
```
-SPARK_HOME ?=/home/y/share/spark
+ifeq ($(shell which spark-submit), "")
+     SPARK_HOME ?=/home/y/share/spark
+else
+     SPARK_HOME ?=$(shell which spark-submit 2>&1 | sed 's/\/bin\/spark-submit//g')
+endif

```

**Comment by arundasan91** [comment]
Wow. That is excellent. Please add this to the Makefile. It will definitely make a smooth workflow.

**Comment by junshi15** [comment]
@arundasan91 I have merged this PR. https://github.com/yahoo/CaffeOnSpark/pull/168

Can you rebase your code? also, please squash your commits. thanks.

**Comment by anfeng** [comment]
Actually, we could simply close this PR if #168 works.

**Comment by arundasan91** [comment]
@anfeng , shall I close this PR then ?
Thanks.

**Comment by anfeng** [comment]
Let's close it once you confirmed PR #168 works.

Andy

**Comment by arundasan91** [comment]
@junshi15 , I'm having trouble with Git. I'm still in the learning phase. I think I'm doing more harm than good by trying things.

@anfeng , In the Makefile, we should replace `awk '{print $$5}'` to `cut -d' ' -f10` in line 13.

**Pull request closed without merging**
