### PR TITLE
enhance cos layer

### PR DESCRIPTION
**Pull request by junshi15**
wait for PR in caffe-public

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by anfeng** [comment]
https://github.com/yahoo/caffe/pull/6 has been merged

**Comment by anfeng** [comment]
Please update caffe-public link

**Comment by junshi15** [comment]
changed caffe-public link already. ready for merge.

**Comment by anfeng** [comment]
+1

**Pull request merged**
