### PR TITLE
Wrap with a for loop while sending&receiving header

### PR DESCRIPTION
**Pull request by zhichao-li**
Sometimes the stream socket might input or output fewer bytes than requested due to the buffer limits or interruption.Normally we would wrap the read & write socket methods within a loop to remedy the problem of "ERROR: Read partial messageheader" which would be triggered occasionally while running CaffeOnSpark via tcp on 8 nodes.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mriduljain** [comment]
Will need to check as we haven't got a problem unless your network has
issues. Anyway thanks for the pull request, will take a look

**Comment by mriduljain** [comment]
+1

**Pull request merged**
