### PR TITLE
Upgraded to Spark 2.0. Contains  breaking changes - not backwards…

### PR DESCRIPTION
**Pull request by javadba**
… compatible.

### CODE REVIEW

**Comment by junshi15** [comment]
Thanks for your contribution. I have a few comments/questions.

1) Spark 2.0 is still in "preview". Can we defer this PR until it is officially released? 

2) What do you mean by "backward compatibility to Spark 1.X", your pom.xml specifies Spark 2.0, so it will be built with Spark 2.0. Do you mean I can take the compiled jar file and launch it with Spark 1.6.1, which is the latest release?

3) Why do you need a new Logger? I notice you copy it from org.apache.spark.internal. Does the existing Logger in CaffeOnSpark not meet your needs?

**Comment by javadba** [comment]
Superseded by  https://github.com/yahoo/CaffeOnSpark/pull/79

**Comment by javadba** [comment]
@junshi15   

I have built a completely new PR #79 that makes the whole process simpler.   
https://github.com/yahoo/CaffeOnSpark/pull/79

To answer your questions:

1)  My team is building only on top of Spark 2.0 . At the very least *we* need this presently.  It is my intention to help out the overall project . 

My original PR recommended  to maintain a separate 2.0-only branch.   @mriduljain  requested to make it backwards compatible on same branch : so the new PR addresses this.

2) New PR takes care of this.

3)  The Logger is required because of one of CaffeOnSpark classes improperly depends on internal Spark Logging class - which is noted  in 1.x to be deprecated for external use and in fact is private in 2.X.  Take a look at  LmdbRDD  "with Logging".

**Comment by mriduljain** [comment]
This looks fine. I will test out locally soon and then we should be good. Meanwhile you should be able to move ahead anyway.

**Pull request closed without merging**
